Reformat code, turn "before_script" into "install"

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -45,28 +45,22 @@ cache:
     - $ANDROID_HOME
     - $SDK_ROOT/flutter
 
-before_script:
+# When one of the steps in the install fails, the build stops immediately and is
+# marked as errored.
+install:
   - mkdir -p "${SDK_ROOT?}"
 
-  - |
-    # Install and configure gcloud
-    curl -sSL \
-    'https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-227.0.0-darwin-x86_64.tar.gz' | \
-    tar -C "${SDK_ROOT?}" -xz
+  # Install and configure gcloud
+  - curl -sSL https://sdk.cloud.google.com |
+    bash -s -- --disable-prompts --install-dir="${SDK_ROOT?}" >/dev/null
+  # This is needed only for iOS to fetch Fastlane match keys repository.
+  - git config --global credential.https://source.developers.google.com.helper
+    gcloud.sh
   - gcloud version
-  # This is needed only for iOS to fetch match keys repository.
-  - |
-    git config --global credential.https://source.developers.google.com.helper \
-        gcloud.sh
 
-  - |
-    # Install and build flutter (may be cached)
-    if hash flutter; then
-      flutter upgrade
-    else
-      git clone --depth=2 --branch=beta https://github.com/flutter/flutter.git \
-          "${SDK_ROOT?}/flutter"
-    fi
+  # Install and build flutter (may be cached)
+  - flutter upgrade || git clone --depth=2 --branch=beta
+    https://github.com/flutter/flutter.git "${SDK_ROOT?}/flutter"
   - flutter precache
   - flutter --version
 
@@ -103,6 +97,8 @@ before_script:
   # TODO(dotdoom): this step is very slow and should not even be necessary.
   - pod setup
 
+# When one of the build commands returns a non-zero exit code, the Travis CI
+# build runs the subsequent commands as well, and accumulates the build result.
 script:
   - ( cd flutter && bundle exec fastlane build )
 
@@ -123,37 +119,39 @@ script:
 
       # We use this account to access both Google Play account and GCS.
       # The former requires it to be in the location configured in Appfile.
-      echo "${GCLOUD_SERVICE_KEY}" | base64 --decode > flutter/android/app/play-store-service-account.json
-      gcloud auth activate-service-account --key-file flutter/android/app/play-store-service-account.json
+      echo "${GCLOUD_SERVICE_KEY}" | base64 --decode > \
+          flutter/android/app/play-store-service-account.json
+      gcloud auth activate-service-account --key-file \
+          flutter/android/app/play-store-service-account.json
 
       mkdir -p ~/.android
       gsutil cp gs://dasfoo-keystore/debug.keystore ~/.android/
       gsutil cp gs://dasfoo-keystore/delern.jks flutter/android/app/
 
       bundle exec fastlane ensure_clean_git &&
-      PROJECT=delern-debug npm --prefix firebase run deploy &&
-      PROJECT=delern-e1b33 npm --prefix firebase run deploy &&
-      ( cd flutter && bundle exec fastlane android publish ) &&
+        PROJECT=delern-debug npm --prefix firebase run deploy &&
+        PROJECT=delern-e1b33 npm --prefix firebase run deploy &&
+        ( cd flutter && bundle exec fastlane android publish ) &&
 
-      if [ -n "$TRAVIS_TAG" ]; then
-        echo 'Building a tag. Upload to TestFlight.'
-        ( cd flutter && bundle exec fastlane ios publish )
-      elif [[ "$TRAVIS_BRANCH" == "master" ]]; then
-        echo 'Building "master" branch. Build debug version, sign. Do not'
-        echo 'upload to TestFlight (review process is too slow, besides,'
-        echo 'version number format will look like a.b.c-N-gCOMMIT, which is'
-        echo 'not accepted by Apple Store).'
+        if [ -n "$TRAVIS_TAG" ]; then
+          echo 'Building a tag. Upload to TestFlight.'
+          ( cd flutter && bundle exec fastlane ios publish )
+        elif [[ "$TRAVIS_BRANCH" == "master" ]]; then
+          echo 'Building "master" branch. Build debug version, sign. Do not'
+          echo 'upload to TestFlight (review process is too slow, besides,'
+          echo 'version number format will look like a.b.c-N-gCOMMIT, which is'
+          echo 'not accepted by Apple Store).'
 
-        ( cd flutter && bundle exec fastlane ios build )
-      else
-        echo 'Unexpected condition for triggering the build!' >&2
-        false
-      fi
+          ( cd flutter && bundle exec fastlane ios build )
+        else
+          echo 'Unexpected condition for triggering the build!' >&2
+          false
+        fi
     else
       echo 'Building a PR. No access to keys. Build debug version w/o signing.'
-      ( cd flutter && bundle exec fastlane android build ) &&
+      ( cd flutter && bundle exec fastlane android build )
       # TODO(dotdoom): write proper lane for fastlane.
-      ( cd flutter && flutter build ios --debug --no-codesign ) &&
+      ( cd flutter && flutter build ios --debug --no-codesign )
       bundle exec fastlane ensure_clean_git
     fi
 
